### ISSUE TITLE
Autocompletion for MonoBehaviour is Incorrect

### ISSUE THREAD

**Issue by Draco18s** [oferei/sublime-unity-completions#9]
Its either the entire MonoBehaviour hierarchy is missed, or the "this" hierarchy.  I'm hazarding the former, as I was able to get it to autocomplete a function I added to a class, but was unable to get it to suggest "this.gameObject" ( http://docs.unity3d.com/401/Documentation/ScriptReference/Component-gameObject.html?from=MonoBehaviour ), it kept wanting to insert a class definition, eg. "this.Component.gameObject" (and the options available do not include MonoBehaviour and all treat the result as a static field of the class, which is incorrect).

It also appears that it is unable to autocomplete for any fields added to any referenced classes.  E.g. if I add a field to a class called Main, then reference an instance of Main, I can't get an autocompletion for its member fields or methods.  eg.:
Main mainRef;
mainRef.someProp = true; //not autocompleted, but exists
mainRef.doTheThing(); //not autocompleted, but exists
this.doSomething(); //autocompleted (although parens and any parameters are omitted)

Autocompleting "GameObject.find" results in "GameObject.GameObject.Find(string name)" which is wrong, on account of the duplicate class reference which won't compile: `UnityEngine.GameObject' does not contain a definition for `GameObject'

I'm coming back from a long hiatus away from Unity, having been over in Java using Eclipse, and I find my editors sorely lacking (and I broke MonoDevelop trying to get a newer version working, after finding serious bugs).  Eclipse showed me how awesome a good IDE is and now I want those tools for the other languages I work in.  A friend suggested Sublime Text, but without good autocompletion for both the Unity namespace and my project namespace, I will not find developing a large project enjoyable.

**Comment by oferei** [comment]
it's not missing the entire MonoBehaviour, but it does not know anything about "this".

let me try to explain. to get excellent auto-completion you need to write an intellisense engine - a plugin that would read all the source files in the project, parse them and determine all variable types. then it could offer only the completions that are relevant. but, alas, this plugin does not do all that. it humbly offers auto-completions for Unity terms that were taken from the scripting documentation. this of course has its limitations. for example, the plugin does not recognize "this" because "this" is not a Unity keyword. but it recognizes MonoBehaviour, which is a type. more on this <a href="https://github.com/oferei/sublime-unity-completions#limitations">here</a>.

regarding "gameObject", MonoBehaviour inherits that member from the Component class. currently the plugin does not offer auto-completions for inherited members/functions. I think I did that because it would add too many irrelevant auto-completions. but anyway, perhaps the plugin should complete MonoBehaviour.gameObject, even if it's inherited. I'll need to rethink this (opened issue #10).

I agrees that without auto-completions it's quite hard to work. and I wish Unity would support some IDE other than Visual Studio. (maybe Sublime?)

**Comment by Draco18s** [comment]
>  also wish that Unity would support some IDE other than Visual Studio. (maybe Sublime?)
That'd be nice.

And thanks for the reply.  I know Eclipse has spoiled me, but at the same time it's more of a shocker that I've not used a single editor that comes close to holding a candle to it, ever.  Maybe Visual Studio, I'm not sure, I've never had to use it much and certainly not to the degree that I now know I want.

**Comment by oferei** [comment]
Visual Studio is very good - better than Eclipse for sure IMHO. the only reason I'm not working with VS is that I'm programming in Boo.
